# Generated by Django 6.0.2 on 2026-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_time',
            field=models.CharField(default='A combinar', help_text='Ex: 2 dias úteis, 5 horas', max_length=50),
            preserve_default=False,
        ),
    ]
