# Generated by Django 6.0.2 on 2026-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AddField(
            model_name='product',
            name='finishings',
            field=models.ManyToManyField(blank=True, to='products.finishing', verbose_name='Acabamentos'),
        ),
    ]
