# Generated by Django 5.1.15 on 2026-02-11 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_finishing_product_is_featured_product_finishings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Formato recomendado: 800x1000px (Retrato)', null=True, upload_to='banners/', verbose_name='Imagem Mobile (Vertical)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link de Destino'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Ex: 1234567890', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Ex: G-XXXXXXXXXX', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigável para SEO', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='Cole aqui o iframe do Google Maps', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
