# Generated by Django 5.1.15 on 2026-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_banner_options_banner_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upsell_products',
            field=models.ManyToManyField(blank=True, help_text="Selecione produtos para a seção 'Compre Junto'", to='products.product'),
        ),
    ]
