# Generated by Django 5.1.15 on 2026-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_kit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitPopupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome interno para identificação', max_length=100)),
                ('image', models.ImageField(help_text='Banner que aparecerá (Ex: 600x400px)', upload_to='popups/')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativar Pop-up?')),
                ('minimum_cart_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Mostrar apenas se o carrinho for maior que...', max_digits=10)),
                ('timer_minutes', models.IntegerField(default=5, help_text='Tempo do contador regressivo (em minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuração do Pop-up',
                'verbose_name_plural': 'Configurações do Pop-up',
            },
        ),
    ]
