# Generated by Django 5.1.15 on 2026-02-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_exitpopupconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpopupconfig',
            name='coupon_code',
            field=models.CharField(default='BEMVINDO', help_text='Código do cupom que será copiado (Ex: PRIMEIRACOMPRA)', max_length=50),
        ),
    ]
