# Generated by Django 5.1.15 on 2026-02-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_exitpopupconfig_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_meter_price',
            field=models.BooleanField(default=False, help_text='Marque se este produto usa calculadora de largura x altura (ex: Lonas, Adesivos)', verbose_name='Vendido por M²'),
        ),
    ]
