# Generated by Django 5.1.15 on 2026-02-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_is_meter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Ex: Digite 15 para dar 15% de desconto no produto e em todas as suas variações.', verbose_name='Desconto (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False, help_text='Marque para ativar o selo piscando e o preço com desconto.', verbose_name='Em Promoção?'),
        ),
    ]
